-- 보호소 들어오기 전 + 중성화 전 동물 번호 
SELECT A.ANIMAL_ID
, A.ANIMAL_TYPE
, A.NAME

FROM
(SELECT ANIMAL_ID
 , ANIMAL_TYPE
 , NAME
 FROM ANIMAL_INS 
 WHERE SEX_UPON_INTAKE NOT IN ('Spayed Female','Neutered Male')
) A 
LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.SEX_UPON_OUTCOME IN ('Spayed Female','Neutered Male')
ORDER BY A.ANIMAL_ID ASC
