
SELECT A.PRODUCT_ID
, A.PRODUCT_NAME
, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES

FROM FOOD_PRODUCT A
INNER JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TO_CHAR(B.PRODUCE_DATE,'YYYY-MM') = '2022-05'

GROUP BY A.PRODUCT_ID
, A.PRODUCT_NAME

ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC

/*
SELECT PRODUCT_ID
 , TO_CHAR(PRODUCE_DATE,'YYYY-MM') AS PRODUCE_DATE
 , AMOUNT
FROM FOOD_ORDER 
WHERE TO_CHAR(PRODUCE_DATE,'YYYY-MM') = '2022-05'
*/

