SELECT CATEGORY 
, PRICE
, PRODUCT_NAME
-- 카테고리별 MAX 가격
FROM FOOD_PRODUCT
WHERE (CATEGORY,PRICE) IN (SELECT CATEGORY 
,MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유')
GROUP BY CATEGORY
)
ORDER BY PRICE DESC

